version: '3.8'
services:
  nginx:
    image: sanagno/multi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    restart: always

  client:
    image: sanagno/multi-client:latest
    restart: always

  api:
    image: sanagno/multi-server:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    restart: always

  worker:
    image: sanagno/multi-worker:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: always